apiVersion: apps/v1
kind: Deployment
metadata:
  name: cic-logger
spec:
  selector:
    matchLabels:
      app: cic-logger
  replicas: 1
  template:
    metadata:
      labels:
        app: cic-logger
    spec:
      containers:
        - name: cic-logger
          image: d0fc41ec9cbe4bdebd01d7b30df6209b.azurecr.io/cic-logger:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              port: 5000
              path: /
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              port: 5000
              path: /
            initialDelaySeconds: 5
            timeoutSeconds: 10
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: cic-logger
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: cic-logger
