apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moviematch-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /middleware(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: middleware
                port:
                  number: 80
          - path: /cic-watcher(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cic-watcher
                port:
                  number: 80
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: middleware
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moviematch-ingress-static
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /static/$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /static(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: middleware
                port:
                  number: 80
