apiVersion: v1
kind: Service
metadata:
  name: azure-containerized-albert-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: azure-containerized-albert
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5500
